services:
  api:
    image: node:20-alpine
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    working_dir: /app
    env_file:
      - '.env'
    command:
      - 'npm'
      - 'run'
      - 'dev'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - '.env'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
